log4j.rootLogger=DEBUG, stdout, logfile
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c.%M()]- %m%n
log4j.appender.logfile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.logfile.DatePattern='.'yyyy-MM-dd
log4j.appender.logfile.File=D:/MonLog/monarch.log
log4j.appender.logfile.MaxFileSize=10MB
# Keep three backup files.
log4j.appender.logfile.MaxBackupIndex=10
# Pattern to output: date priority [category] - message
log4j.appender.logfile.layout=org.apache.log4j.PatternLayout
#log4j.appender.logfile.layout.ConversionPattern=%d %p [%c] - %m%n
log4j.appender.logfile.layout.ConversionPattern=%d %p [%c.%M()]- %m%n
# Root logger option
#log4j.rootLogger=INFO, stdout
#log4j.appender.stdout=org.apache.log4j.ConsoleAppender
#log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
#log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - %m%n
#log4j.appender.stdout.layout.ConversionPattern=%d %p [%c.%M]- %m%n


#Spring JdbcTemplate logging
log4j.logger.org.springframework.jdbc.core.JdbcTemplate=DEBUG, springlogfile
log4j.logger.org.springframework.jdbc.core.NamedParameterJdbcTemplate=DEBUG, springlogfile

log4j.appender.springlogfile=org.apache.log4j.DailyRollingFileAppender
log4j.appender.springlogfile.DatePattern='.'yyyy-MM-dd
log4j.appender.springlogfile.File=D:/MonLog/springJdbcTemplate.log
log4j.appender.springlogfile.MaxFileSize=10MB
# Keep three backup files
log4j.appender.springlogfile.MaxBackupIndex=10
log4j.appender.springlogfile.layout=org.apache.log4j.PatternLayout
# Pattern to output&#58; date priority &#91;category&#93; - <message>line_separator
log4j.appender.springlogfile.layout.ConversionPattern=%d %p &#91;%c&#93; - <%m>%n