############# \uacf5\uc601\ubcf8\uc0ac MONARCH815 \ub370\uc774\ud130\uc18c\uc2a4 ################
#\uac1c\ubc1c\uc11c\ubc84 \uc624\ub77c\ud074
#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@xxx.xxx.xxx.xx:1521:MON
#jdbc.username=xxxxxx
#jdbc.password=xxxxxx

############# MariaDB ################
#MariaDB Datasource Properties
#jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.driverClassName=org.mariadb.jdbc.Driver
#jdbc.url=ENC(d91tmUmhm+2PTkG5vSa6AdaLWwG/1SyorzDbPmCWublk+9A9kryVUHutLDv7jVkQB/OBpO+qQncX8IbuLAA4Mp+HxBOEtL4pD4goecg8yDs=)
#jdbc.username=ENC(8bkknUR9U4UT24ns3lWRRUy+VwAe9YRv)
#jdbc.password=ENC(XccolMHWodYf6K2QL42p+dqYvHivI9oO)

############# \uacf5\uc601\ubcf8\uc0ac MONARCH815 \ub370\uc774\ud130\uc18c\uc2a4 ################
##\uac1c\ubc1c\uc11c\ubc84 \uc624\ub77c\ud074
#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=ENC(g2Ui3SejQqqK7tTQsChjZ+tbLbYiSdAVp8SOOmzaD0mYyu5LP0eqMZz8rzmpEQ04)
##monarch Demo
##jdbc.username=ENC(yDF4cCOqwd1eCls8vMy2+Q==)
##monarch Core
#jdbc.username=ENC(vPD1LAcxpkRelMLZwKodo4QB2AS+36+I)
#jdbc.password=ENC(cRl+JtwoFf4ANi2nx4MK7PYSYAZMl24M)


#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@localhost:1521:orcl
#jdbc.username=monarch815
#jdbc.password=kydbm7206828

#CRM DEV SERVER
jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
jdbc.url=jdbc:oracle:thin:@182.198.77.11:1621:MICRODEV
#jdbc.url=ENC(WK6ftB5YVoyZW6w0FtLGj9B5ysp8Zlj1MP1G8/tbs3m4oDEmFhKXOczgpVqbHXnIA/TkSvtmTnA=)
jdbc.username=crm
jdbc.password=crm00db

#CRM OPT SERVER
#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
##jdbc.url=jdbc:oracle:thin:@192.168.147.156:1621:MICRODB
#jdbc.url=ENC(ueM0rigT5qgPEAhieu/kOFw1kwCOn7K8pUSqjGYjXqBx3n1IpGHFhmfR/KWOjTSMY3qqhDZGaXE=)
#jdbc.username=crm
#jdbc.password=crm00db


#jdbc.driverClassName=oracle.jdbc.driver.OracleDriver
#jdbc.url=jdbc:oracle:thin:@119.69.119.84:1521:xe
#jdbc.username=mon
#jdbc.password=kydbm7206828
