#\ubaa8\ub098\ud06c \uae30\ubcf8\uc815\ubcf4
# \ubaa8\ub098\ud06c \uba54\uc778 \uae30\ub3d9 DB\uc120\ud0dd \ud604\uc7ac \uc9c0\uc6d0DB: oracle, mssql, postgres,mariadb 
#monarch.db.type = mariadb
monarch.db.type = oracle
#\uac1c\ubc1c\uc11c\ubc84
monarch.url =http://192.168.1.39:8080
#\uac1c\ubc1c\uc11c\ubc84 \ubaa8\ubc14\uc77c
#monarch.url.mobile =http://192.168.1.39:8080
#\ud30c\uc77c\uc800\uc7a5 \uc11c\ubc84\uc8fc\uc18c
monarch.url.fileserver =http://192.168.1.39:8080
#\uc6f9\ucee8\ud150\uce20 \ubb3c\ub9ac\ud328\uc2a4
monarch.url.realpath = D:/Monarch810ForJava/MonarchWorkSpace/Monarch820/WebContent/
#monarh.url.realpath = /usr/Application/newvoc/newvoc.ear/newvocWeb.war/

####### \uc5c5\ub85c\ub4dc\ud30c\uc77c \uc0ac\uc774\uc988 \uc81c\ud55c 20MB\ub85c \ub514\ud3f4\ud2b8 #######
#\uc2e4\uc81c\ub85c monarch-servlet.xml\uc5d0\ub3c4 \uc218\uc815\uc774 \ud544\uc694\ud568.(20MB\ub85c \uc124\uc815\ub418\uc5b4\uc788\uc74c)
monarch.fileupload.limitsize = 20000000
monarch.fileupload.path = D:/Monarch810ForJava/MonarchWorkSpace/Monarch820/WebContent/



####### \ub2e4\uc774\ub809\ud2b8\uba54\uc77c #######
email.indv.unit = 100
#\ub2e4\uc774\ub809\ud2b8\uba54\uc77c \ubaa8\ub4dc[0:\ud14c\uc2a4\ud2b8\ubaa8\ub4dc 1: \uc6b4\uc601\ubaa8\ub4dc ]
email.indv.mode = 1
email.indv.test.tomail = khma@00db.co.kr
#email.smtp.host = 192.168.1.12
#email.smtp.id = gL9V+INENgD/el686mXqiQ==
#email.smtp.password = U8O3hLNJ6XlLaiCvbVi8TPC/hTEdKL9799HIvirYabI=
email.smtp.host = 121.78.144.225
email.smtp.id = u9g6XpCHOUgpx3q44Jah11hkDgBQn+qh
email.smtp.password = Kt0dMc68KYY9Lwq65dGX+Wfh/ea4GfP4
#directmail.host  = 
#directmail.mode =0
#directmail.test.tomail = jwkim2@00db.co.kr
#directmail.test.frommail =  jwkim2@00db.co.kr
#directmail.imgfile.width = 300;
#directmail.imgfile.height = 300;
########################


####### \ubc30\uce58\ucc98\ub9ac\uad00\ub828  #######
####\ubd80\uc11c\ub3d9\uae30\ud654\ubc30\uce58####
#\ud14c\uc2a4\ud2b8\ud30c\uc77c\ud328\uc2a4
#scheduler.syncdept.filepath = d:/FileData/dept_erp.tbl

#### \ubc30\uce58\ucc98\ub9ac \uc0ac\uc6a9\uc5ec\ubd80 ####
#\ubd80\uc11c\ub3d9\uae30\ud654\ubc30\uce58 \uc0ac\uc6a9\uc5ec\ubd80(true: \uc0ac\uc6a9 false:\ubbf8\uc0ac\uc6a9)
#scheduler.syncdept.execflag = false
########################

 

